name: whatsapp_clone
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# ---------------  PACKAGES -------------------#
dependencies:
  flutter:
    sdk: flutter


  # Utility Packages
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9

  # State Management 
  get: ^4.6.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/images/splash/
    - assets/images/country_flags/
    - assets/images/icons/
    - assets/images/profile_pics/
    - assets/images/background/

  # Fonts
  fonts:
    - family: helvetica-light
      fonts:
        - asset: assets/fonts/helvetica-light.ttf

    - family: helvetica-regular
      fonts:
        - asset: assets/fonts/helvetica-regular.ttf

    - family: helvetica-bold
      fonts:
        - asset: assets/fonts/helvetica-bold.ttf

